---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ca
  labels:
    run: blockchain-ca
spec:
  type: NodePort
  selector:
    name: ca
  ports:
  - protocol: TCP
    targetPort: 7054
    port: 30054
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer
  labels:
    run: blockchain-orderer
spec:
  type: NodePort
  selector:
    name: orderer
  ports:
  - protocol: TCP
    targetPort: 31010
    port: 31010
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org1peer1
  labels:
    run: blockchain-org1peer1
spec:
  type: NodePort
  selector:
    name: org1peer1
  ports:
  - protocol: TCP
    port: 30110
    name: grpc
  - protocol: TCP
    port: 30111
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb


---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-org2peer1
  labels:
    run: blockchain-org2peer1
spec:
  type: NodePort
  selector:
    name: org2peer1
  ports:
  - protocol: TCP
    port: 30210
    name: grpc
  - protocol: TCP
    port: 30211
    name: events
  - protocol: TCP
    port: 5984
    name: couchdb
