kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "aws-efs"
  name: common-pvc
  labels:
    app: blockchain
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
