---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchdb-pvc1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 3Gi


---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchdb-pvc2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: aws-efs
  resources:
    requests:
      storage: 3Gi